# Generated by Django 3.0.10 on 2020-10-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('IT', 'Italian'), ('I', 'Indian'), ('M', 'Thai'), ('C', 'Caribbean')], max_length=2),
        ),
    ]
